title: "Michelle Yang"
author: "Michelle Yang"
email: michelleziqi@gmail.com
future: true
permalink: /:categories/:title:output_ext
excerpt_separator: "\n\n\n"

remote_theme: niklasbuschmann/contrast@v2.11
plugins:
  - jekyll-remote-theme
  
# Layout
show_frame: true

navigation:
  - {file: "index.html", title:"Home", icon: home}
  - {file: "index.html", title:"CV", icon: CV}
